apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-msa-app
  namespace: default  # ArgoCD 설정에서 맞춘 네임스페이스와 동일해야 함
  labels:
    app: flask-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        # [주의] 본인의 Docker Hub ID로 변경하세요 (예: kildong/flask-app:latest)
        image: 2sohyun/flask-app:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: default
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
